# Generated by Django 4.2.5 on 2023-10-15 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workSector', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('workSector',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('ItemCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.itemcode')),
            ],
        ),
    ]
