# Generated by Django 4.2.5 on 2023-10-16 10:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.CharField(max_length=100)),
                ('contractorType', models.CharField(choices=[('CIV', 'Civil'), ('SAN', 'Sanitary'), ('CAR', 'Carpenter'), ('THA', 'Thai and Glass'), ('PLU', 'Plumber'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('address', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
            options={
                'ordering': ('contractor',),
            },
        ),
        migrations.CreateModel(
            name='OfficeItemCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sector', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('Sector',),
            },
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareholderName', models.CharField(max_length=100)),
                ('numberOfFlat', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ('-numberOfFlat',),
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('itemName',)},
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemCode', to='Accounts.itemcode'),
        ),
        migrations.CreateModel(
            name='ShareholderDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfTransaction', models.DateField(default=datetime.datetime.now)),
                ('modeOfDeposit', models.CharField(choices=[('CASH', 'Cash'), ('CHEQ', 'Cheque'), ('OTHE', 'Other')], default='OTHE', max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ShareholderDeposit', to='Accounts.shareholder')),
            ],
            options={
                'ordering': ('-dateOfTransaction',),
            },
        ),
        migrations.CreateModel(
            name='OfficeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('officeitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officeitem', to='Accounts.officeitemcode')),
            ],
            options={
                'ordering': ('itemName',),
            },
        ),
        migrations.CreateModel(
            name='OfficeExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfTransaction', models.DateField(default=datetime.datetime.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(default='LS', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voucherNo', models.CharField(default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_expenditure', to='Accounts.item')),
            ],
            options={
                'ordering': ('-dateOfTransaction',),
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfTransaction', models.DateField(default=datetime.datetime.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(default='LS', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voucherNo', models.CharField(default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Expenditure', to='Accounts.item')),
            ],
            options={
                'ordering': ('-dateOfTransaction',),
            },
        ),
        migrations.CreateModel(
            name='ContractorBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfTransaction', models.DateField(default=datetime.datetime.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContractorBill', to='Accounts.contractor')),
            ],
        ),
    ]
