# Generated by Django 4.2.5 on 2023-10-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_contractor_officeitemcode_shareholder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoggedinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitorIP', models.CharField(blank=True, max_length=200, null=True, verbose_name='visitorIP')),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('country_code', models.CharField(blank=True, max_length=200, null=True)),
                ('continent', models.CharField(blank=True, max_length=200, null=True)),
                ('continent_code', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('county', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('region_code', models.CharField(blank=True, max_length=200, null=True)),
                ('timezone', models.CharField(blank=True, max_length=200, null=True)),
                ('owner', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(blank=True, max_length=200, null=True)),
                ('languages', models.CharField(blank=True, max_length=200, null=True)),
                ('visitCount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Visitor Count')),
                ('visitDateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
