# Generated by Django 4.2.5 on 2023-10-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_userloggedinfailed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userloggedinfailed',
            old_name='pasword',
            new_name='password',
        ),
    ]
