# Generated by Django 4.2.5 on 2023-10-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_rename_pasword_userloggedinfailed_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='Mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='NID',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='TIN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='TelephoneNo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile No.'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='nid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NID No.'),
        ),
    ]
