# Generated by Django 4.2.5 on 2023-12-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_alter_shareholder_numberofflat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='email',
            field=models.EmailField(blank=True, max_length=300, null=True, verbose_name='Email'),
        ),
    ]
