# Generated by Django 5.0 on 2023-12-24 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_alter_shareholder_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractorType', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='contractor',
            name='contractorType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contr_Type', to='Accounts.contractortype'),
        ),
    ]
