# Generated by Django 5.0 on 2023-12-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_contractortype_alter_contractor_contractortype'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorbill',
            name='labor_fooding',
            field=models.DecimalField(default=models.Value(0), decimal_places=2, max_digits=10),
        ),
    ]
