# Generated by Django 5.0 on 2023-12-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_contractorbill_labor_fooding'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='rate',
            field=models.DecimalField(db_default=models.Value(0), decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='quantity',
            field=models.DecimalField(db_default=models.Value(0), decimal_places=2, max_digits=10),
        ),
    ]
