# Generated by Django 5.0 on 2023-12-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_expenditure_rate_alter_expenditure_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
