# Generated by Django 5.0 on 2024-01-02 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_alter_item_options_shareholder_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='dateOfJoin',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='dateOfJoin',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
