# Generated by Django 5.0 on 2024-01-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_targetedamount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractorBill',
            new_name='ContractorBillPayment',
        ),
        migrations.AlterModelOptions(
            name='targetedamount',
            options={'ordering': ('-inputDate',)},
        ),
    ]
