# Generated by Django 5.0 on 2024-01-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0018_contractorbillpayment_voucherno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorbillpayment',
            name='remarks',
            field=models.CharField(default='', max_length=200),
        ),
    ]
