# Generated by Django 5.0 on 2024-01-15 13:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0019_alter_contractorbillpayment_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfPurchase', models.DateField(default=datetime.datetime.now)),
                ('seller', models.CharField(default='', max_length=150)),
                ('address', models.CharField(default='', max_length=250)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.CharField(default='', max_length=250)),
            ],
            options={
                'ordering': ('-dateOfPurchase',),
            },
        ),
        migrations.AddField(
            model_name='expenditure',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Contractor', to='Accounts.contractor'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CreditPurchase', to='Accounts.creditpurchase'),
        ),
    ]
