# Generated by Django 5.0 on 2024-01-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0020_creditpurchase_expenditure_contractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpurchase',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
    ]
