# Generated by Django 5.0 on 2024-01-16 06:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0021_creditpurchase_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfTransaction', models.DateField(default=datetime.datetime.now)),
                ('description', models.CharField(default='', max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.CharField(default='', max_length=250)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seller', to='Accounts.creditpurchase')),
            ],
            options={
                'ordering': ('-dateOfTransaction',),
            },
        ),
    ]
