# Generated by Django 5.0 on 2024-01-16 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0022_creditpurchasepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CreditPurchasePayment', to='Accounts.creditpurchasepayment'),
        ),
    ]
