# Generated by Django 5.0 on 2024-01-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0023_alter_expenditure_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpurchasepayment',
            name='voucherNo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
