# Generated by Django 5.0 on 2024-01-17 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0026_creditpurchasepayment_item_alter_expenditure_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractorbillpayment',
            name='contractor',
        ),
        migrations.AddField(
            model_name='contractorbillpayment',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bill_submission', to='Accounts.contractorbillsubmission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractorbillsubmission',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_bill', to='Accounts.contractor'),
        ),
    ]
