# Generated by Django 5.0 on 2024-01-17 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0027_remove_contractorbillpayment_contractor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='contractor',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='contractor_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_bill', to='Accounts.contractorbillpayment'),
        ),
    ]
