# Generated by Django 5.0 on 2024-01-17 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0028_remove_expenditure_contractor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditure',
            old_name='contractor_bill',
            new_name='contractor_bill_payment',
        ),
    ]
