# Generated by Django 5.0 on 2024-01-17 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0029_rename_contractor_bill_expenditure_contractor_bill_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditure',
            old_name='seller',
            new_name='credit_purchase_payment',
        ),
    ]
