# Generated by Django 5.0 on 2024-01-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0030_rename_seller_expenditure_credit_purchase_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorbillpayment',
            name='labor_fooding',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
