# Generated by Django 5.0 on 2024-01-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0031_alter_contractorbillpayment_labor_fooding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloggedinrecord',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
