# Generated by Django 4.2.9 on 2024-03-02 05:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0032_userloggedinrecord_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomeSector', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
                ('incomeSector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Income_Sector', to='Accounts.incomesector')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfTransaction', models.DateField(default=datetime.datetime.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(default='LS', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voucherNo', models.CharField(default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Income_Item', to='Accounts.incomeitem')),
            ],
            options={
                'ordering': ('-dateOfTransaction',),
            },
        ),
    ]
