# Generated by Django 4.2.9 on 2024-03-02 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0033_incomesector_incomeitem_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomeitem',
            old_name='description',
            new_name='unit',
        ),
    ]
