# Generated by Django 4.2.9 on 2024-03-02 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0034_rename_description_incomeitem_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='item',
            new_name='IncomeItem',
        ),
    ]
