# Generated by Django 4.2.9 on 2024-03-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0035_rename_item_income_incomeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
