# Generated by Django 4.2.9 on 2024-03-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0036_alter_income_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
