# Generated by Django 4.2.9 on 2024-03-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0037_income_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='IncomeItem',
            new_name='incomeItem',
        ),
    ]
